### ISSUE TITLE
cli flag name "location" rather than "directory" on model samples on website resulting in error

### ISSUE THREAD

**Issue by TirelessClock** [intel/dffml#1371]
@programmer290399 @pdxjohnny @mHash1m 
I was running some of the CLI model implementations on the [Quickstart Page](https://intel.github.io/dffml/master/quickstart/model.html) and the [Models Page](https://intel.github.io/dffml/master/plugins/dffml_model.html) (slr, scikitlr etc.) and I ran into the following error: 

![Screenshot 2022-04-30 at 9 11 26 PM](https://user-images.githubusercontent.com/92638241/166112424-da3a82f5-6e22-48f9-b662-fe180f887400.png)

I noticed this issue in several of the models (slr, scikitlr, tensorflow etc.). After some tinkering, I found that the issue was fixed upon replacing the "-model-location" flag with "-model-directory". 

Please inform if I'm implementing it wrong or if this is a genuine issue with the sample text on the website. In the latter case, I would like to work on the same. 

Thanks!

**Comment by mHash1m** [comment]
@TirelessClock This is probably a clash b/w the version of dffml you are running and the version of docs you are using to copy quick start commands.
Make sure it is the same. If your local is up to date with master, make sure to use the master branch docs.

**Comment by TirelessClock** [comment]
@mHash1m Sorry, I didn't understand the reason for the error. 
I'm using DFFML v0.4.0 and python v3.7 and my local is up to date with master.
Please help. Thanks!

**Comment by mHash1m** [comment]
No worries.
You are running v0.4.0 of DFFML but the commands you are using aren't part of the release. These commands can only be used on the master branch.
So if you want to run commands on 0.4.0, use the commands [here on the 0.4.0 docs quickstart guide](https://dffml.github.io/dffml-pre-image-removal/quickstart/model.html)
Otherwise setup master on your local using [this guide](https://intel.github.io/dffml/master/contributing/dev_env.html), then you will be able to run the commands you were running before (ones for master branch)

**Comment by TirelessClock** [comment]
@mHash1m 
Oooh, right. I get it now. TYSM!
