### ISSUE TITLE
ci: Whitespace checker broken

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#232]
`.ci/run.sh` whitespace checking function is broken. It should exit non-zero if there is any trailing whitespace in the repo

**Comment by beinganonymous** [comment]
@pdxjohnny i would like to work on this.

**Comment by pdxjohnny** [comment]
@beinganonymous Awesome! Thanks!

**Comment by drigio** [comment]
Hey @pdxjohnny initial looks at the code in ``.ci/run.sh`` looks good. Also I took a look at previous builds on travis and it has a good history. Running the code locally on pc (I ran only the ``run_whitespace()`` function) works properly. When I add an extra whitespace line in any file it duly shows that there are trailing whitespaces.

Checking the exit code by using ``echo $?`` returns 1 i.e. non-zero as well. 
What you think @beinganonymous ? 
Are you getting some different output @pdxjohnny ? Because I guess Linux distribution and its accompanying toolset (find, grep) etc may matter too.

I am running a distribution that inherits Ubuntu 18.04 LTS.

**Comment by pdxjohnny** [comment]
Huh, maybe its not broken then. I'll have to check last time I tried it didn't exit 1, which is why I made the issue. Thanks for validating @drigio! I appreciate it, probably something wrong with my machine then. Let me see if I can reproduce by own bug lol

**Comment by beinganonymous** [comment]
@drigio when i am checking the exit code using ``echo $?`` it returns 0.
I am using Ubuntu 16.04 LTS.

**Comment by beinganonymous** [comment]
@pdxjohnny are you expecting trailing whitespace as a space bar or tab at end or as a new line at the end ?

**Comment by beinganonymous** [comment]
Hey @pdxjohnny  your ``run_whitespace()`` function work properly with ``Ubuntu 18.04``, but i guess it has issues with ``Ubuntu 16.04``.
I have created this script which work fine with Ubuntu 18.04 and 16.04.
```
    for file in `find $1 -type f -name "*.py"`;
    do
        nlines=`tail -n 1 $file | grep '^$' | wc -l`
        if [ $nlines -eq 1 ]
                then echo $file
        fi
     done;
```
Should i send in PR for that?
What you think @pdxjohnny .
What your thoughts about the code @drigio .

**Comment by beinganonymous** [comment]
Hey @pdxjohnny  your ``run_whitespace()`` function work properly with ``Ubuntu 18.04``, but i guess it has issues with ``Ubuntu 16.04``.
I have created this script which work fine with Ubuntu 18.04 and 16.04.
```
    for file in `find $1 -type f -name "*.py"`;
    do
        nlines=`tail -n 1 $file | grep '^$' | wc -l`
        if [ $nlines -eq 1 ]
                then echo $file
        fi
     done;
```
Should i send in PR for that?
What you think @pdxjohnny ?
What your thoughts about the code @drigio ?

**Comment by pdxjohnny** [comment]
GitHub Actions does not experiance this issue: 70ce150
