### ISSUE TITLE
source: db: Source using the database abstraction

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#402]
In https://github.com/intel/dffml/commit/7a80ac8bea7af104aea2290b6761737f594bb320 the database abstraction was added. It would be nice if we could leverage that to create a source which takes a database in it's config. So that whatever database abstractions people implement (such as [sqlite](https://github.com/intel/dffml/commit/7a80ac8bea7af104aea2290b6761737f594bb320) and [mysql](https://github.com/intel/dffml/commit/29eeb2e7136fc8e1659c63e4b9ab88963384cd3d)) this source can use any of them.

**Comment by Lactem** [comment]
@pdxjohnny would you please let me know if [my skeleton](https://github.com/Lactem/dffml/commit/14efc0e2286b01578a9e3e21c2d3e00ecdde7ab0) is on the right path? I realize I didn't use the dffml service command to auto-copy the whole skeleton, but I'll get to that eventually. It'll help me understand the project better if I copy over each file manually.

Were you thinking the source would have a config option that says which db to point to, and then the source would use the db's config and abstracted insert/update/remove/etc methods to access records? I want to make sure I'm on the right track before I fill in too much.

**Comment by pdxjohnny** [comment]
> @pdxjohnny would you please let me know if [my skeleton](https://github.com/Lactem/dffml/commit/14efc0e2286b01578a9e3e21c2d3e00ecdde7ab0) is on the right path? I realize I didn't use the dffml service command to auto-copy the whole skeleton, but I'll get to that eventually. It'll help me understand the project better if I copy over each file manually.

Awesome! It's very close, I left a few comments.

> Were you thinking the source would have a config option that says which db to point to, and then the source would use the db's config and abstracted insert/update/remove/etc methods to access records? I want to make sure I'm on the right track before I fill in too much.

I left some comments about the config, let me know if anything is unclear. I'd say try making a source that doesn't do anything (`return` right away for each of the required methods), figure out how to get the test_dbsource.py set up. Then use the abstracted insert/update/remove/etc methods to access records. Not sure if this helps, let me know when you're ready for more feedback.

Thanks! :)

**Comment by Lactem** [comment]
Thanks for all the guidance. I haven't had a chance to look at your feedback yet, but it looks like I have a lot to work with. I'll plan to push what I have later this week.

**Comment by pdxjohnny** [comment]
Of course! Thanks for the contribution! :) Just ping me whenever you want further review. It also would be good to open a PR with `WIP:` as the prefix (Work In Progress) so that we and comment back and forth in that interface.

**Comment by Lactem** [comment]
I came to a decent stopping point with a few questions. The first is about syntax - I notice underscore and camelCase for variables and methods. I could've missed it but I don't see an official stance on that bit in the docs.

More importantly, I'm requesting some guidance on testing (as well as making sure the rest of the implementation is on track so far). I left some TODO comments in test_source.py under source/db/tests and made the PR you requested, so you should be able to comment in that interface. What do you think?

Less relevant -- I noticed that the BaseDatabase abstraction supports tables and rows and columns, so is it really more of a base SQL abstraction rather than an abstraction for all dbs? Looks like there's a SQLDatabaseContext but no corresponding SQLBaseDatabase. Maybe we would add something else for Mongo or other NoSQL options in the future? I initially thought a non-relational database wouldn't be well suited for ML but [this article](https://www.mongodb.com/blog/post/training-machine-learning-models-with-mongodb) makes a case for it (I think the gist is that they used a generator function to get the Mongo data into a ML-ready matrix).

**Comment by pdxjohnny** [comment]
> I came to a decent stopping point with a few questions. The first is about syntax - I notice underscore and camelCase for variables and methods. I could've missed it but I don't see an official stance on that bit in the docs.
> 
> More importantly, I'm requesting some guidance on testing (as well as making sure the rest of the implementation is on track so far). I left some TODO comments in test_source.py under source/db/tests and made the PR you requested, so you should be able to comment in that interface. What do you think?
> 
> Less relevant -- I noticed that the BaseDatabase abstraction supports tables and rows and columns, so is it really more of a base SQL abstraction rather than an abstraction for all dbs? Looks like there's a SQLDatabaseContext but no corresponding SQLBaseDatabase. Maybe we would add something else for Mongo or other NoSQL options in the future? I initially thought a non-relational database wouldn't be well suited for ML but [this article](https://www.mongodb.com/blog/post/training-machine-learning-models-with-mongodb) makes a case for it (I think the gist is that they used a generator function to get the Mongo data into a ML-ready matrix).

**Comment by pdxjohnny** [comment]
Oops didn't mean to close
