### ISSUE TITLE
ci: 0.3.7: TensorFlow 2.3.0 doesn't work with numpy 1.19.1

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#816]
```
2020-07-27T19:25:00.0718202Z pkg_resources.ContextualVersionConflict: (numpy 1.19.1 (/usr/share/miniconda/lib/python3.7/site-packages), Requirement.parse('numpy<1.19.0,>=1.16.0'), {'tensorflow'})
```

**Comment by pdxjohnny** [comment]
We tried pinning tensorflow to < 2.3.0 but no relief yet.

This issue https://github.com/pypa/pip/issues/8076 captures some of what the core problem is here. Ideally we'd have some sort of per-package virtualenv.

To focus on the matter at hand though, we need to understand what package is causing a onflicting version range and see if we can do something similar to what was done with scipy

**Comment by 0dust** [comment]
Looks like conda is the culprit here.

**Comment by pdxjohnny** [comment]
Does anyone know if this has been fixed? @sudharsana-kjl  @yashlamba  @0dust @sakshamarora1 @aghinsa (pinging you all because one of you is probably most likely to have checked / can check)

**Comment by 0dust** [comment]
@pdxjohnny This issue is still going on: https://github.com/tensorflow/models/issues/9200
Workaround is to either use tensorflow 2.2 or pin numpy to some version <1.19.1
Few day back I tried pinning it to 1.18.5, it seems to be working: https://github.com/0dust/dffml/tree/resolve_tf_conflict_with_np

**Comment by pdxjohnny** [comment]
@0dust Thank you for the update!
